name: Deploy to Azure Container Instance

on:
  push:
    branches:
      - master
  workflow_dispatch:

env:
  CONTAINER_NAME: auth-services
  RESOURCE_GROUP: DreamCanvas
  IMAGE_NAME: ghcr.io/lianyic/dreamcanvas-auth-service:latest
  DATABASE_URL:  ${{ secrets.DATABASE_URL }}

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v4

    - name: Login to GitHub Container Registry
      run: echo "${{ secrets.GIT_TOKEN }}" | docker login ghcr.io -u ${{ 5hub.actor }} --password-stdin

    - name: Build Docker Image
      run: docker build -t $IMAGE_NAME .

    - name: Push Docker Image to GHCR
      run: docker push $IMAGE_NAME

    - name: Azure Login
      uses: azure/login@v1
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}

    - name: Delete existing Azure Container Instance (if exists)
      continue-on-error: true
      run: |
        az container delete --resource-group $RESOURCE_GROUP --name $CONTAINER_NAME --yes

    - name: Create new Azure Container Instance
      run: |
        az container create \
          --resource-group $RESOURCE_GROUP \
          --name $CONTAINER_NAME \
          --image $IMAGE_NAME \
          --dns-name-label dreamcanvas-auth \
          --ports 5000 \
          --cpu 1 \
          --memory 1 \
          --os-type Linux \
          --environmen23t-variables DATABASE_URL= ${{ secrets.DATABASE_URL }}